// Known LightMetrics account IDs, used only to populate a <datalist> of
// suggestions for the Client ID field. The field stays free text — there is no
// accounts-list endpoint, so this is a convenience for typing, not a
// whitelist. Anything typed is submitted as-is; the backend is the authority
// on which accounts a given user may actually load.
export const CLIENT_IDS = [
  'abaxeu', 'actsoft', 'advancedtms', 'advtracking', 'allcomtelecom', 'argus',
  'assetlivetrack', 'assetproadvantage', 'astussis', 'attrix', 'avasolutions',
  'beepview', 'beyondclarity', 'bigchange', 'blackboxcontrol', 'buswhereus',
  'calamp', 'calamp_exp', 'calampprodeu', 'calampprodus', 'calampqaus',
  'calampstageus', 'cerebrumx', 'charteredgreentech', 'cloudrentaus', 'cobli',
  'coltrack', 'connectm', 'cpxytest', 'cslau', 'cslnz', 'demoaps1', 'demousw2',
  'dicv', 'digicore', 'digitalmatter', 'digitalmatterdemo', 'dpl',
  'dpltelematics', 'dqtechcan', 'dqtechstagingus', 'dqtechus', 'dtna',
  'easitrack', 'easybox', 'evolutiondata', 'ezytrack', 'fc1eu', 'fc1prod',
  'fc1qa', 'fc1uat', 'fc1util', 'fcgeotabaus', 'fcprodaus', 'feqatesting',
  'fleetdynamics', 'fleetforce', 'fleetlocate', 'fleetlog', 'fleettracking',
  'gausscontrol', 'geoboxau', 'geosecure', 'geotab', 'globalelectronetworks',
  'gpsafe', 'gpsboss', 'gpsiau', 'grupoempresarial', 'hatten', 'helix',
  'ignitionprod', 'ignitionstaging', 'intellitrac', 'inthinc', 'iotab',
  'iotrack', 'iseeyoutechnologies', 'itssa', 'keeptrackgps', 'kynection',
  'leadingedgeinnovations', 'lightmetrics_qa', 'lmbackendcanada', 'lmbackendqa',
  'lmdemodubai', 'lmdemotsp', 'lmpresales', 'lmqaapse2', 'lmqaeuc1',
  'lmqatesting1', 'lmqatesting2', 'lmsdkdev', 'lmssotest', 'lmtspwarehouse',
  'lmvisionqa', 'machinemax', 'machinemaxuae', 'mactrackau', 'managemyfleet',
  'maticx', 'matrixza', 'michelin', 'michelineu', 'michelineustaging',
  'michelinnastaging', 'mitac', 'mobi7', 'mojio1', 'mojioprod',
  'mooveconnected', 'moter', 'motorq0', 'mx4track', 'myanmarparama', 'navixy',
  'navixyeu', 'navixyus', 'nbindustries', 'nedtracking', 'nlmjtech',
  'onlinesolutions', 'orbcomm', 'orbcomm_dev', 'orbcomm_exp', 'orbcommdev',
  'osmoworld', 'pascalcomputers', 'pedigree', 'platformscience',
  'platformsciencestg', 'powerfleet', 'presalesaus', 'proconwarehouse',
  'prometheuspro', 'pwflvisionaiint', 'pxproduction', 'pxstaging', 'quantatec',
  'radius', 'rearviewsafety', 'reddtrack', 'rededgeresources', 'roadview360',
  'roqit0', 'rotagyn', 'rvindiadirect', 'rysevision', 'safefleet', 'satrack',
  'satrackstaging', 'satrackusa', 'securitysystempng', 'segmovil', 'sensium',
  'simplyunified', 'skyetrack', 'skylinegps', 'solera', 'soleracan',
  'soleramain', 'soleramoter', 'soleramx', 'solerauk', 'solusimonitoring',
  'spireon', 'spireonstage', 'stsunlab', 'suntechdobrasil', 'suntechlatam',
  'suntechlatamsa', 'taabi', 'targatelematics', 'tarosolutions', 'tcvsat',
  'teletracnavman', 'teletracnavmanausprod', 'teletracnavmanmxprod',
  'teletracnavmanukprod', 'teletracnavmanusprod', 'teletracnavmanusqa',
  'teletracnavmanusstg', 'terminusgps', 'tgtracking', 'toyotafm', 'tracker',
  'tractics', 'turingriskservices', 'vecvin', 'veriserv', 'volvoaaos',
  'waypointiot', 'webtrack', 'willworks', 'zctest', 'zinier', 'zonarsystems',
]
